source: "."
dest: "build"
posts: "articles"
drafts: "_drafts"
rss: rss.xml
name: Jeroen's Blog
description: Jeroen Cops, personal website
link: https://jeroencops.github.io
ignore:
  - .git/*
  - build/*
