sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    rust: nightly
cache: cargo
before_script:
  - cd ..
  - git clone https://github.com/cobalt-org/cobalt.rs.git
  - ls
  - cd cobalt.rs
  - cargo install --force || true
  - export PATH="$PATH:/home/travis/.cargo/bin"
  - cobalt --version
  - cd ..
  - ls
  - cd target
script:
  - cobalt build
after_succes: |
  [ $TRAVIS_BRANCH = source ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cobalt import --branch master &&
  git config user.name "Cobalt Site Deployer" &&
  git config user.email "jernncops@live.be" &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
