sudo: false
language: rust
rust:
  - stable
cache: cargo
before_script:
  - cd ..
  - git clone https://github.com/cobalt-org/cobalt.rs.git
  - cd cobalt.rs
  - cargo install --force || true
  - export PATH="$PATH:/home/travis/.cargo/bin"
  - cd ..
  - cd JeroenCops.github.io/src
script:
  - cobalt --version
  - cobalt build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  target_branch: master
  on:
    all_branches: true
